version: '3.8'

x-nginx-log-generator:
  &nginx-log-generator
  build: log-generator-nginx
  volumes: 
    - generated_log:/data
  
x-filebeat:
  &filebeat
  image: docker.elastic.co/beats/filebeat:8.3.3
  user: root
  depends_on:
    - app


services:
  app:
    <<: *nginx-log-generator
    networks:
      - monitoring-flow
  
  filebeat:
    <<: *filebeat
    volumes: 
      #filebeat 설정파일을 mount
      - generated_log:/usr/share/filebeat/log
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw    
    networks:
      - monitoring-flow          
    
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9104:9100
    networks:
      - monitoring-flow
    
  cadvisor:  
    image: google/cadvisor:latest  
    privileged: true
    volumes:  
      - /:/rootfs:ro  
      - /var/run:/var/run:ro  
      - /sys:/sys:ro  
      # install in ubuntu
      #- /var/lib/docker/:/var/lib/docker:ro  
      # install in wsl
      - /mnt/windows_docker/:/rootfs/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro  
    ports:
      - 9105:9101
    networks:
      - monitoring-flow
    

volumes:
  generated_log:


networks:
  monitoring-flow: